show = true

[number]
	x = -200
	y = 90
	#Range: 0.0 ~ 10.0
	scale = 2.5
	show = true
	#Range: 0.0 ~ 1.0
	opacity = 1.0

[title]
	x = -200
	y = 72
	#Range: 0.0 ~ 10.0
	scale = 2.8
	show = true
	#Range: 0.0 ~ 1.0
	opacity = 1.0

[combo]
	x = -205
	y = 114
	#Range: 0.0 ~ 10.0
	scale = 1.2
	show = true
	#Range: 0.0 ~ 1.0
	opacity = 1.0

[damage_list]
	x = -155
	y = 90
	#Range: 0.0 ~ 10.0
	scale = 0.8
	show = true
	#Range: 0.0 ~ 1.0
	opacity = 1.0
	max_size = 8

[damage_rank]
	#Use damage ranked style
	enable = true
	#Use format like "<damage amount>|<rank name>|<render color>"
	option = ["0|Â§oÂ§lğ”»|#ffffff", "10|Â§oÂ§lâ„‚|#F5DEB3", "20|Â§oÂ§lğ”¹|#F4A460", "30|Â§oÂ§lğ”¸|#FF8C00", "40|Â§oÂ§lğ•Š|#FF6347", "60|Â§oÂ§lğ•Šğ•Š|#FF4500", "80|Â§oÂ§lğ•Šğ•Šğ•Š|#FF0000"]

	[damage_rank.color]
		#Color the damage number
		number = true
		#Color the title
		title = true
		#Color the title
		combo = false

[combo_rank]
	#Use combo ranked style
	enable = false
	#Use format like "<combo>|<rank name>|<render color>"
	option = ["0|D|#ffffff", "5|C|#e6fffb", "10|B|#bae7ff", "20|A|#bae637", "40|S|#fff566", "80|SS|#ffbb96", "160|SSS|#ffa39e"]

	[combo_rank.color]
		#Color the damage number
		number = true
		#Color the title
		title = true
		#Color the combo
		combo = true

